config/routes.rb
HknRails::Application.routes.draw do

  match "courseguides", to: "courseguides#index", via: :get, as: "courseguides"
  match "courseguides/:dept/:name", to: "courseguides#show", via: :get, as: "courseguide_show"
  match "courseguides/edit/:dept/:name", to: "courseguides#edit", via: :get, as: "courseguide_edit"
  match "courseguides/edit/:dept/:name", to: "courseguides#update", via: :post, as: "courseguides_update"

  root to: "pages#home"

  devise_for :users, controllers: { registrations: "registrations" }

  match 'notifications/read', to: 'notifications#index', via: :get, as: "notifications"

  match "dept_tours/success", to: "dept_tours#success", via: :get, as: "dept_tours_success"
  match "dept_tours/:id", to: "dept_tours#respond_to_tour", via: :post
  match "exams/search(/:q)", to: "exams#search", via: :get, :as => :exams_search
  match "exams/course/:dept_abbr/:full_course_number", to: "exams#course", via: :get, :as => :exams_course
  match "users/approve/:id", to: "users#approve", via: :post, as: "users_approve"
  match "users/list(/:category)", to: "users#list", via: :get, as: "users_list"
  match "users/roles/:id", to: "users#roles", via: :get, as: "edit_roles_user"
  match "users/roles/:id", to: "users#alter_roles", via: :post, as: "alter_roles_user"
  match "resumes/upload_for/:user_id" => "resumes#upload_for", via: :get, :as => :resumes_upload_for
  match "resumes/:id/download" => "resumes#download", via: :get, :as => :resume_download
  match "resumes/status_list" => "resumes#status_list", via: :get, :as => :resumes_status_list
  match "resume_books/:id/download_pdf" => "resume_books#download_pdf", via: :get, :as => :resume_book_download_pdf
  match "resume_books/:id/download_iso" => "resume_books#download_iso", via: :get, :as => :resume_book_download_iso
  match "resume_books/missing" => "resume_books#missing", via: :post, :as => :resume_book_missing
  match "resume_books/missing" => "resume_books#missing", via: :get, :as => :resume_book_missing_get
  match 'resumes/include/:id' => "resumes#include", via: :post, :as => :resumes_include
  match 'resumes/exclude/:id' => "resumes#exclude", via: :post, :as => :resumes_exclude
  match 'staff_members_merge' => 'staff_members#merge', via: :get, as: :staff_members_merge
  match 'staff_members_merge' => 'staff_members#merge_post_setup', via: :post, as: :staff_members_merge_post
  match 'staff_members_commit' => 'staff_members#merge_post_commit', via: :post, as: :staff_members_merge_post_commit
  match 'autocomplete_staff_members', to: 'staff_members#autocomplete_staff_members_name', via: :get, as: :autocomplete_staff_members_name

  match 'autocomplete_course_names', to: 'courses#autocomplete_course_names', via: :get, as: :autocomplete_course_name

  match "coursesurveys/course/:dept/:name", to: "coursesurveys#show", via: :get, :as => :coursesurveys_course
  match "coursesurveys/course/:dept", to: "coursesurveys#department", via: :get, :as => :coursesurveys_department
  match "coursesurveys/how-to", to: "pages#coursesurveys_how_to", via: :get, :as => :coursesurveys_how_to
  match "coursesurveys/info-profs", to: "pages#coursesurveys_info_profs", via: :get, :as => :coursesurveys_info_profs
  match "coursesurveys/ferpa", to: "pages#coursesurveys_ferpa", via: :get, :as => :coursesurveys_ferpa

  match 'staff_members/staff/:instructors', to: 'staff_members#instructors', via: :get, as: :staff_member_instructors

  resources :alum
  resources :announcements
  resources :challenges, only: [:create, :update, :index]
  resources :companies
  resources :contacts
  resources :courses
  resources :coursesurveys
  resources :dept_tours
  resources :exams
  resources :indrel_event_types
  resources :indrel_events
  resources :locations
  resources :resumes
  resources :resume_books, except: [:edit, :update]
  resources :resume_book_urls
  resources :staff_members
  resources :users, except: [:new, :create, :index]

  scope "events" do
    match "leaderboard(/:semester)", to: "events#leaderboard", via: :get, as: :event_leaderboard
    match "rsvps", to: "rsvps#my_rsvps", via: :get, as: :my_rsvps
    match "calendar", to: "events#calendar", via: :get, as: "events_calendar"
    match ":category", to: "events#index", via: :get, as: :events_category, constraints: {:category => /(future|past)/}
    # Routes for RSVP confirmation page
    match "confirm_rsvps/:role" => "events#confirm_rsvps_index", via: :get, :as => :confirm_rsvps_index
    match "confirm_rsvps/:role/event/:id" => "events#confirm_rsvps", via: :get, :as => :confirm_rsvps
    match "confirm/:id" => "rsvps#confirm", via: :get, :as => :confirm_rsvp
    match "unconfirm/:id" => "rsvps#unconfirm", via: :get, :as => :unconfirm_rsvp
    match "reject/:id" => "rsvps#reject", via: :get, :as => :reject_rsvp
  end

  resources :events do
    resources :rsvps, shallow: true
  end

  scope "candidate" do
    match "quiz", to: "candidate#quiz", via: :get, as: "candidate_quiz"
    match "submit_quiz", to: "candidate#submit_quiz", via: :post, as: "candidate_submit_quiz"
    match "portal", to: 'candidate#portal', via: :get, as: "candidate_portal"
    match "application", to: 'candidate#application', via: :get, as: "candidate_application"
    match "application", to: 'candidate#submit_app', via: :post, as: "candidate_submit_app"
    match "autocomplete_officer_name", to: "candidate#autocomplete_officer_name", via: :get, as: "autocomplete_officer_name"
  end

  scope "indrel" do
    match "/", to: "indrel#why_hkn", via: :get, as: "indrel"
    match "contact_us", to: "indrel#contact_us", via: :get, as: "indrel_contact_us"
    match "career_fair", to: "indrel#career_fair", via: :get, as: "career_fair"
    match "resume_books", to: "indrel#resume_books", via: :get, as: "resume_books_about"
    match "resume_books/order", to: "indrel#resume_books_order", via: :get, :as => "resume_books_order"
    match "resume_books/order", to: "indrel#resume_books_transaction_id", via: :post, :as => "resume_books_transaction_id"
    match "resume_books/success", to: "indrel#resume_books_order_paypal_success", via: :get, :as => "resume_books_paypal_success"
    match "resume_books/order_email", to: "indrel#resume_books_order_email", via: :get, :as => "resume_books_order_email"
    match "resume_books/order_email", to: "indrel#resume_books_order_email_post", via: :post, :as => "resume_books_order_email_post"
    # post  "resume-books/order_email"        => "indrel#resume_book_order_post",        :as => "resume_book_order_post"
    scope "infosessions" do
      match "/", to: "infosession_requests#about", via: :get, as: "infosessions"
      match "registration", to: "infosession_requests#new", via: :get, as: "new_infosession_request"
      match "registration", to: "infosession_requests#create", via: :post, as: "create_infosession_request"
    end
  end

  #About HKN
  scope 'about' do
    match 'contact', to: "pages#contact", via: :get, as: "about_contact"
    match 'officers(/:semester)', to: "pages#officers", via: :get, as: "about_officers"
    match 'committee_members(/:semester)', to: "pages#committee_members", via: :get, as: "about_committee_members"
  end

  scope 'bridge' do
    resources :slideshows
    resources :yearbooks
  end

  namespace :admin do
    scope "csec" do
      match "/", to: "csec#index", via: :get, as: :csec
      match "select_classes", to: "csec#select_classes", via: :get, as: :csec_select_classes
      match "select_classes", to: "csec#select_classes_post", via: :post, as: :csec_select_classes_post
      match "manage_classes", to: "csec#manage_classes", via: :get, as: :csec_manage_classes
      match "manage_classes", to: "csec#manage_classes_post", via: :post, as: :csec_manage_classes_post
      match "manage_candidates", to: "csec#manage_candidates", via: :get, as: :csec_manage_candidates
      match "upload_surveys", to: "csec#upload_surveys", via: :get, as: :csec_upload_surveys
      match "upload_surveys", to: "csec#upload_surveys_post", via: :post, as: :csec_upload_surveys_post
      match 'coursesurveys/:id', to: 'csec#coursesurvey_show', via: :get, as: :csec_coursesurvey
      match 'coursesurveys/:coursesurvey_id/remove/:user_id', to: 'csec#coursesurvey_remove', via: :delete, as: :csec_coursesurvey_remove
    end
    scope "vp" do
      match "/", to: "vp#index", via: :get, as: :vp
      match "applications", to: "vp#applications", via: :get, as: :cand_applications
      match "applications/byperson", to: "vp#byperson", via: :get, as: :cand_byperson
      match "applications/bycommittee", to: "vp#bycommittee", via: :get, as: :cand_bycommittee
      match "applications/byperson_withoutapp", to: "vp#byperson_without_application", via: :get, as: :cand_byperson_without_application
      match "super_page(/:semester)", to: "vp#super_page", via: :get, as: :vp_super_page
      match "promote_candidate_path", to: "vp#promote_candidate", via: :post, as: :vp_promote_candidate
    end
    match "pres", to: "pres#index", via: :get, as: :pres
    scope "bridge" do
      match "/", to: "bridge#index", via: :get, as: :bridge
      match "officer_photo_upload", to: "bridge#officer_photo_index", via: :get, as: :bridge_officer_index
      match "officer_photo_upload", to: "bridge#officer_photo_upload", via: :post, as: :bridge_officer_upload
    end
    scope "indrel" do
      match "/", to: "indrel#index", via: :get, as: :indrel
    end
    scope "studrel" do
      match "/", to: "studrel#index", via: :get, as: :studrel
    end
  end

end

app/models/alum.rb
# == Schema Information
#
# Table name: alumni
#
#  id            :integer          not null, primary key
#  grad_semester :string(255)
#  grad_school   :string(255)
#  job_title     :string(255)
#  company       :string(255)
#  salary        :integer
#  user_id       :integer
#  perm_email    :string(255)
#  location      :string(255)
#  suggestions   :text
#  mailing_list  :boolean
#  created_at    :datetime
#  updated_at    :datetime
#

class Alum < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :user_id
  validates_inclusion_of :salary,
      :in => 0...5000000000000000000,
      :message=>"must be within 0 and 5 quintillion",
      :allow_nil=>true
  validates_presence_of :perm_email, :grad_semester
  before_save :wants_emails?

  def wants_emails?
    if mailing_list_changed? && mailing_list
      self.subscribe
    elsif mailing_list_was && !mailing_list # mailing list just changed from true to false
      self.unsubscribe
    end
  end

  MAILING_LIST_URL = 'https://hkn.eecs.berkeley.edu/mailman/listinfo/alumni'
  SEASONS = ['Fall', 'Spring', 'Summer']

  def subscribe
    agent = Mechanize.new
    agent.get(MAILING_LIST_URL) do |page|
      page.form_with(:action => '../subscribe/alumni') do |form|
        form['email'] = self.perm_email
        form['fullname'] = self.user.full_name
      end.submit
    end
  end

  def unsubscribe
    agent = Mechanize.new
    agent.get(MAILING_LIST_URL) do |page|
      options_page = page.form_with(:action => '../options/alumni') do |form|
        form['email'] = self.perm_email
      end.submit
      options_page.form_with(:action => '../options/alumni') do |form|
        form.click_button(form.button_with(:value => 'Unsubscribe'))
      end
    end
  end

  def self.grad_semester(semester, year)
    return semester + ' ' + year
  end

  def get_username
    self.user.username
  end

  def self.years
    current = Time.now.year
    return (1915..current).to_a.reverse
  end
end

app/controllers/alum_controller.rb
class AlumController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_alum, only: [:show, :edit, :update, :destroy]
  before_filter :my_alum_or_alumrel!, :only => [:show, :edit, :update, :destroy]
  before_filter :authenticate_alumrel!, only: [:index]
  before_filter :input_helper, :only => [:create, :update]
  before_filter :alumni_duplication_filtration, :only => [:new, :create]

  def my_alum_or_alumrel!
    @alum.user.id == current_user.id || authenticate_alumrel! # will redirect the user if both fail
  end

  # GET /alumni
  def index
    @alumni = Alum.all.includes(:user)
  end

  # GET /alumni/1
  def show
  end

  def alumni_duplication_filtration
    if current_user.alum
      redirect_to edit_alum_path(current_user.alum),
          notice: "You already have an alumni record. I've helpfully brought it up for you."
    end
  end

  # GET /alumni/new
  def new
    @alum = Alum.new
  end

  # GET /alumni/1/edit
  def edit
    grad_semester = @alum.grad_semester.split
    @grad_season = grad_semester[0] # Spring or Fall
    @grad_year = grad_semester[1] # the actual year
  end

  # POST /alumni
  def create
    params[:alum][:grad_semester] = Alum.grad_semester(params[:grad_season], params[:grad_year])
    params[:alum][:user_id] = current_user.id
    @alum = Alum.new(alum_params)

    if @alum.save
      user_session[:alum] = nil # fix the user session, works b/c users can only make alum for themselves
      redirect_to edit_alum_path(@alum), notice: 'Alum was successfully created.'
    else
      render :new
    end
  end

  def input_helper
    #Allow leading $, and seperators of , and _ (strip them)
    params[:alum][:salary].gsub!(/(^\$)|,|_/,'') if params[:alum] && params[:alum][:salary]
  end

  # PATCH/PUT /alumni/1
  def update
    params[:alum][:grad_semester] = Alum.grad_semester(params[:grad_season], params[:grad_year])
    if @alum.update(alum_params)
      redirect_to @alum, notice: 'Alum was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /alumni/1
  def destroy
    @alum.user.update_attribute :should_reset_session, true # just clear the user's session so the alum menu will display properly
    @alum.destroy
    redirect_to new_alum_path, notice: 'Alum was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alum
      @alum = Alum.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def alum_params
      params.require(:alum).permit(:grad_semester, :grad_school, :job_title, :company, :salary, :user_id, :perm_email, :location, :suggestions, :mailing_list)
    end
end

app/views/alum/_form.html.erb
<%= form_for(@alum, :url => alum_path(@alum)) do |f| %>
  <% if @alum.errors.any? %>
    <h2><%= pluralize(@alum.errors.count, "error") %> prohibited this alum from being created:</h2>
    <div class="alert alert-danger">
      <% @alum.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg %>
      <% end %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :perm_email, 'Permanent email' %>
    <%= f.text_field :perm_email, :type => 'email' %>
  </div>
  <div class="field">
    <%= f.label :mailing_list, 'Yes, add me to the alumni mailing list!' %>
    <div>You'll receive periodic news/updates about HKN, including Alumni events.</div>
    <%= f.check_box :mailing_list%>
  </div>
  <div class="field">
    <%= label_tag :grad_semester, 'Semester graduated (from Ugrad)' %>
    <%= select_tag :grad_season, options_for_select(Alum::SEASONS, @grad_semester) %>
    <%= select_tag :grad_year, options_for_select(Alum.years, @grad_year), :style => 'padding-bottom: 10px;' %>
    <br style="clear: both;" />
  </div>
  <div class="field">
    <%= f.label :grad_school %>
    <%= f.text_field :grad_school %>
  </div>
  <div class="field">
    <%= f.label :job_title %>
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :salary %>
    <%= f.text_field :salary, :value => number_to_currency(@alum.salary, :unit => "$", precision: 0) %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :suggestions, 'Have any suggestions for Alumrel?' %>
    <div>(more/different types of alumni activities, etc.)</div>
    <%= f.text_area :suggestions %>
  </div>
  <div class="field-submit">
    <%= f.submit "Submit"%>
  </div>
<% end %>

app/views/alum/edit.html.erb
<h1>Editing alum</h1>

<%= render 'form' %>

<%= link_to 'Show', @alum %> |
<%= link_to 'Destroy', @alum, method: :delete, data: { confirm: 'Are you sure?' } %>
<% if authorize(:alumrel) %>
  | <%= link_to 'Index', alum_index_path %>
<% end %>

app/views/alum/index.html.erb
<h1>Listing alumni</h1>

<table>
  <thead>
    <tr>
      <th>Permanenet email</th>
      <th>Grad semester</th>
      <th>Grad school</th>
      <th>Job title</th>
      <th>Company</th>
      <th>Salary</th>
      <th>Location</th>
      <th>Suggestions</th>
      <th>Username</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @alumni.each do |alum| %>
      <tr>
        <td><%= alum.perm_email %></td>
        <td><%= alum.grad_semester %></td>
        <td><%= alum.grad_school %></td>
        <td><%= alum.job_title %></td>
        <td><%= alum.company %></td>
        <td><%= number_to_currency(alum.salary, :unit => "$", precision: 0) %></td>
        <td><%= alum.location %></td>
        <td><%= alum.suggestions %></td>
        <td><%= alum.get_username %></td>
        <td><%= link_to 'Show', alum %></td>
        <td><%= link_to 'Edit', edit_alum_path(alum) %></td>
        <td><%= link_to 'Destroy', alum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alum', new_alum_path %>

app/views/alum/new.html.erb
<h1>New alum</h1>

<%= render 'form' %>
<% if authorize(:alumrel) %>
  <%= link_to 'Index', alum_index_path %>
<% end %>

app/views/alum/show.html.erb
<p>
  <strong>Grad semester:</strong>
  <%= @alum.grad_semester %>
</p>

<p>
  <strong>Grad school:</strong>
  <%= @alum.grad_school %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @alum.job_title %>
</p>

<p>
  <strong>Company:</strong>
  <%= @alum.company %>
</p>

<p>
  <strong>Salary:</strong>
  <%= number_to_currency(@alum.salary, :unit => "$", precision: 0) %>
</p>

<p>
  <strong>User:</strong>
  <%= @alum.get_username %>
</p>

<p>
  <strong>Permanent email:</strong>
  <%= @alum.perm_email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @alum.location %>
</p>

<p>
  <strong>Suggestions:</strong>
  <%= @alum.suggestions %>
</p>

<p>
  <strong>Mailing list:</strong>
  <%= @alum.mailing_list %>
</p>

<%= link_to 'Edit', edit_alum_path(@alum) %> |
<%= link_to 'Destroy', @alum, method: :delete, data: { confirm: 'Are you sure?' } %>
<% if authorize(:alumrel) %>
  | <%= link_to 'Index', alum_index_path %>
<% end %>