config/routes.rb
HknRails::Application.routes.draw do

  match "courseguides", to: "courseguides#index", via: :get, as: "courseguides"
  match "courseguides/:dept/:name", to: "courseguides#show", via: :get, as: "courseguide_show"
  match "courseguides/edit/:dept/:name", to: "courseguides#edit", via: :get, as: "courseguide_edit"
  match "courseguides/edit/:dept/:name", to: "courseguides#update", via: :post, as: "courseguides_update"

  root to: "pages#home"

  devise_for :users, controllers: { registrations: "registrations" }

  match 'notifications/read', to: 'notifications#index', via: :get, as: "notifications"

  match "dept_tours/success", to: "dept_tours#success", via: :get, as: "dept_tours_success"
  match "dept_tours/:id", to: "dept_tours#respond_to_tour", via: :post
  match "exams/search(/:q)", to: "exams#search", via: :get, :as => :exams_search
  match "exams/course/:dept_abbr/:full_course_number", to: "exams#course", via: :get, :as => :exams_course
  match "users/approve/:id", to: "users#approve", via: :post, as: "users_approve"
  match "users/list(/:category)", to: "users#list", via: :get, as: "users_list"
  match "users/roles/:id", to: "users#roles", via: :get, as: "edit_roles_user"
  match "users/roles/:id", to: "users#alter_roles", via: :post, as: "alter_roles_user"
  match "resumes/upload_for/:user_id" => "resumes#upload_for", via: :get, :as => :resumes_upload_for
  match "resumes/:id/download" => "resumes#download", via: :get, :as => :resume_download
  match "resumes/status_list" => "resumes#status_list", via: :get, :as => :resumes_status_list
  match "resume_books/:id/download_pdf" => "resume_books#download_pdf", via: :get, :as => :resume_book_download_pdf
  match "resume_books/:id/download_iso" => "resume_books#download_iso", via: :get, :as => :resume_book_download_iso
  match "resume_books/missing" => "resume_books#missing", via: :post, :as => :resume_book_missing
  match "resume_books/missing" => "resume_books#missing", via: :get, :as => :resume_book_missing_get
  match 'resumes/include/:id' => "resumes#include", via: :post, :as => :resumes_include
  match 'resumes/exclude/:id' => "resumes#exclude", via: :post, :as => :resumes_exclude
  match 'staff_members_merge' => 'staff_members#merge', via: :get, as: :staff_members_merge
  match 'staff_members_merge' => 'staff_members#merge_post_setup', via: :post, as: :staff_members_merge_post
  match 'staff_members_commit' => 'staff_members#merge_post_commit', via: :post, as: :staff_members_merge_post_commit
  match 'autocomplete_staff_members', to: 'staff_members#autocomplete_staff_members_name', via: :get, as: :autocomplete_staff_members_name

  match 'autocomplete_course_names', to: 'courses#autocomplete_course_names', via: :get, as: :autocomplete_course_name

  match "coursesurveys/course/:dept/:name", to: "coursesurveys#show", via: :get, :as => :coursesurveys_course
  match "coursesurveys/course/:dept", to: "coursesurveys#department", via: :get, :as => :coursesurveys_department
  match "coursesurveys/how-to", to: "pages#coursesurveys_how_to", via: :get, :as => :coursesurveys_how_to
  match "coursesurveys/info-profs", to: "pages#coursesurveys_info_profs", via: :get, :as => :coursesurveys_info_profs
  match "coursesurveys/ferpa", to: "pages#coursesurveys_ferpa", via: :get, :as => :coursesurveys_ferpa

  match 'staff_members/staff/:instructors', to: 'staff_members#instructors', via: :get, as: :staff_member_instructors

  resources :alum
  resources :announcements
  resources :challenges, only: [:create, :update, :index]
  resources :companies
  resources :contacts
  resources :courses
  resources :coursesurveys
  resources :dept_tours
  resources :exams
  resources :indrel_event_types
  resources :indrel_events
  resources :locations
  resources :resumes
  resources :resume_books, except: [:edit, :update]
  resources :resume_book_urls
  resources :staff_members
  resources :users, except: [:new, :create, :index]

  scope "events" do
    match "leaderboard(/:semester)", to: "events#leaderboard", via: :get, as: :event_leaderboard
    match "rsvps", to: "rsvps#my_rsvps", via: :get, as: :my_rsvps
    match "calendar", to: "events#calendar", via: :get, as: "events_calendar"
    match ":category", to: "events#index", via: :get, as: :events_category, constraints: {:category => /(future|past)/}
    # Routes for RSVP confirmation page
    match "confirm_rsvps/:role" => "events#confirm_rsvps_index", via: :get, :as => :confirm_rsvps_index
    match "confirm_rsvps/:role/event/:id" => "events#confirm_rsvps", via: :get, :as => :confirm_rsvps
    match "confirm/:id" => "rsvps#confirm", via: :get, :as => :confirm_rsvp
    match "unconfirm/:id" => "rsvps#unconfirm", via: :get, :as => :unconfirm_rsvp
    match "reject/:id" => "rsvps#reject", via: :get, :as => :reject_rsvp
  end

  resources :events do
    resources :rsvps, shallow: true
  end

  scope "candidate" do
    match "quiz", to: "candidate#quiz", via: :get, as: "candidate_quiz"
    match "submit_quiz", to: "candidate#submit_quiz", via: :post, as: "candidate_submit_quiz"
    match "portal", to: 'candidate#portal', via: :get, as: "candidate_portal"
    match "application", to: 'candidate#application', via: :get, as: "candidate_application"
    match "application", to: 'candidate#submit_app', via: :post, as: "candidate_submit_app"
    match "autocomplete_officer_name", to: "candidate#autocomplete_officer_name", via: :get, as: "autocomplete_officer_name"
  end

  scope "indrel" do
    match "/", to: "indrel#why_hkn", via: :get, as: "indrel"
    match "contact_us", to: "indrel#contact_us", via: :get, as: "indrel_contact_us"
    match "career_fair", to: "indrel#career_fair", via: :get, as: "career_fair"
    match "resume_books", to: "indrel#resume_books", via: :get, as: "resume_books_about"
    match "resume_books/order", to: "indrel#resume_books_order", via: :get, :as => "resume_books_order"
    match "resume_books/order", to: "indrel#resume_books_transaction_id", via: :post, :as => "resume_books_transaction_id"
    match "resume_books/success", to: "indrel#resume_books_order_paypal_success", via: :get, :as => "resume_books_paypal_success"
    match "resume_books/order_email", to: "indrel#resume_books_order_email", via: :get, :as => "resume_books_order_email"
    match "resume_books/order_email", to: "indrel#resume_books_order_email_post", via: :post, :as => "resume_books_order_email_post"
    # post  "resume-books/order_email"        => "indrel#resume_book_order_post",        :as => "resume_book_order_post"
    scope "infosessions" do
      match "/", to: "infosession_requests#about", via: :get, as: "infosessions"
      match "registration", to: "infosession_requests#new", via: :get, as: "new_infosession_request"
      match "registration", to: "infosession_requests#create", via: :post, as: "create_infosession_request"
    end
  end

  #About HKN
  scope 'about' do
    match 'contact', to: "pages#contact", via: :get, as: "about_contact"
    match 'officers(/:semester)', to: "pages#officers", via: :get, as: "about_officers"
    match 'committee_members(/:semester)', to: "pages#committee_members", via: :get, as: "about_committee_members"
  end

  scope 'bridge' do
    resources :slideshows
    resources :yearbooks
  end

  namespace :admin do
    scope "csec" do
      match "/", to: "csec#index", via: :get, as: :csec
      match "select_classes", to: "csec#select_classes", via: :get, as: :csec_select_classes
      match "select_classes", to: "csec#select_classes_post", via: :post, as: :csec_select_classes_post
      match "manage_classes", to: "csec#manage_classes", via: :get, as: :csec_manage_classes
      match "manage_classes", to: "csec#manage_classes_post", via: :post, as: :csec_manage_classes_post
      match "manage_candidates", to: "csec#manage_candidates", via: :get, as: :csec_manage_candidates
      match "upload_surveys", to: "csec#upload_surveys", via: :get, as: :csec_upload_surveys
      match "upload_surveys", to: "csec#upload_surveys_post", via: :post, as: :csec_upload_surveys_post
      match 'coursesurveys/:id', to: 'csec#coursesurvey_show', via: :get, as: :csec_coursesurvey
      match 'coursesurveys/:coursesurvey_id/remove/:user_id', to: 'csec#coursesurvey_remove', via: :delete, as: :csec_coursesurvey_remove
    end
    scope "vp" do
      match "/", to: "vp#index", via: :get, as: :vp
      match "applications", to: "vp#applications", via: :get, as: :cand_applications
      match "applications/byperson", to: "vp#byperson", via: :get, as: :cand_byperson
      match "applications/bycommittee", to: "vp#bycommittee", via: :get, as: :cand_bycommittee
      match "applications/byperson_withoutapp", to: "vp#byperson_without_application", via: :get, as: :cand_byperson_without_application
      match "super_page(/:semester)", to: "vp#super_page", via: :get, as: :vp_super_page
      match "promote_candidate_path", to: "vp#promote_candidate", via: :post, as: :vp_promote_candidate
    end
    match "pres", to: "pres#index", via: :get, as: :pres
    scope "bridge" do
      match "/", to: "bridge#index", via: :get, as: :bridge
      match "officer_photo_upload", to: "bridge#officer_photo_index", via: :get, as: :bridge_officer_index
      match "officer_photo_upload", to: "bridge#officer_photo_upload", via: :post, as: :bridge_officer_upload
    end
    scope "indrel" do
      match "/", to: "indrel#index", via: :get, as: :indrel
    end
    scope "studrel" do
      match "/", to: "studrel#index", via: :get, as: :studrel
    end
  end

end

app/controllers/admin/csec_controller.rb
class Admin::CsecController < ApplicationController
  before_filter :authenticate_csec!

  def index
  end

  def select_classes
    m_sem = MemberSemester.current
    course_semester = CourseSemester.where(season: m_sem.season, year: m_sem.year).first_or_create
    @offerings = course_semester.course_offerings.includes(:course, :course_survey).order('courses.department', 'courses.course_name')
  end

  def select_classes_post
    m_sem = MemberSemester.current
    course_semester = CourseSemester.where(season: m_sem.season, year: m_sem.year).first_or_create
    course_semester.course_offerings.includes(:course_survey).each do |offering|
      if params.has_key?("offering#{offering.id}") and offering.course_survey.nil?
        # This should not fail
        CourseSurvey.create!(course_offering: offering)
      elsif !params.has_key?("offering#{offering.id}") and !offering.coursesurvey.nil?
        offering.course_survey.delete
      end
    end
    m_sem.coursesurveys_active = !params[:coursesurveys_active].blank?
    m_sem.save
    redirect_to admin_csec_select_classes_path, :notice => "Updated classes to be surveyed"
  end

  def manage_classes
    m_sem = MemberSemester.current
    course_semester = CourseSemester.where(season: m_sem.season, year: m_sem.year).first_or_create
    @coursesurveys = course_semester.course_surveys.includes({course_offering: :course}, :users)
  end

  def manage_classes_post
    params.keys.reject{|x| !(x =~ /^survey[0-9]*$/)}.each do |param_id|
      id = param_id[6..-1]
      coursesurvey = CourseSurvey.find_by_id(id) # This should not fail
      coursesurvey.update_attributes(params[param_id].permit(:status, :max_surveyors))
      redirect_to admin_csec_manage_classes_path, notice: "Error happened. Your input was probably not valid." and return unless coursesurvey.valid?
    end
    redirect_to admin_csec_manage_classes_path, notice: "Updated classes"
  end

  def manage_candidates
    @users = MemberSemester.current.candidates.sort_by(&:full_name)
  end

  def upload_surveys
    @results = {:errors=>[], :info=>[]}
    @success = @allow_save = false
  end

  def upload_surveys_post
    # The actual file upload

    return redirect_to admin_csec_upload_surveys_path, :notice => "Please select a file to upload." unless params[:file]

##    if params[:save] then
##      Process.fork { system "rake db:backup:dump RAILS_ENV=#{Rails.env}" }
##      Process.wait
##    end

    @results    = SurveyData::Importer.import(:csv, params[:file].tempfile, params[:save], params[:ta])
    @success    = @results[:errors].empty?
    @allow_save = @success && !params[:save]
    @ta         = !!params[:ta]
    @results[:errors] << "No data was imported because of the above errors." if !@success && params[:save]
    render 'upload_surveys'

##    unless results[:errors].empty? then
##      return redirect_to admin_csec_upload_surveys_path, :notice => "There was #{results[:errors].length} #{'error'.pluralize_for results[:errors].length} parsing that file:\n#{results[:errors].join('
##')}"   # wtf. it won't take '\n'.
##    else
##      return redirect_to admin_csec_upload_surveys_path, :notice => "Successful upload and parse. Please verify the information below."
##    end
  end

  def coursesurvey_show
    @coursesurvey = CourseSurvey.includes(:users).find_by_id(params[:id])
    redirect_to admin_csec_manage_classes_path, notice: "Invalid coursesurvey ID" and return unless @coursesurvey
  end

  def coursesurvey_remove
    @coursesurvey = CourseSurvey.find_by_id(params[:coursesurvey_id])
    @user = User.find_by_id(params[:user_id])

    return redirect_to admin_csec_manage_classes_path, :notice => "Invalid coursesurvey ID" unless @coursesurvey
    return redirect_to admin_csec_coursesurvey_path(@coursesurvey), notice: "Invalid person ID" unless @user
    return redirect_to admin_csec_coursesurvey_path(@coursesurvey), notice: "#{@user.full_name} is not surveying #{@coursesurvey.course_offering.to_s}" unless @coursesurvey.users.include?(@user)

    @coursesurvey.users.delete(@user)
    @coursesurvey.save

    redirect_to admin_csec_coursesurvey_path(@coursesurvey), :notice => "Removed #{@user.full_name} from #{@coursesurvey.course_offering.to_s} survey"
  end
end

app/views/admin/csec/coursesurvey_show.html.erb
<h1><%= @coursesurvey.course_offering.to_s %></h1>

<div>
  <%- @coursesurvey.users.each do |p| -%>
    <div>
      <%= p.full_name %>
      <%= link_to '[delete]', admin_csec_coursesurvey_remove_path(@coursesurvey.id, p.id), data: { confirm: 'Are you sure?' }, method: :delete %>
    </div>
  <%- end -%>
</div>

<%= link_to '&larr; back'.html_safe, admin_csec_manage_classes_path %>

app/views/admin/csec/index.html.erb
<h1>Corresponding Secretary Admin</h1>
<ul>
  <li><%= link_to 'Select classes to be surveyed this semester', admin_csec_select_classes_path %></li>
  <li><%= link_to 'Manage classes', admin_csec_manage_classes_path %></li>
  <li><%= link_to 'Manage candidates', admin_csec_manage_candidates_path %></li>
  <li><%= link_to 'Upload survey data', admin_csec_upload_surveys_path %></li>
  <li><%= link_to 'Merge survey instructor data', staff_members_merge_path %></li>
  <li><%= link_to 'Edit courses', courses_path %></li>
  <li><%= link_to 'New instructor', new_staff_member_path %></li>
</ul>

app/views/admin/csec/manage_candidates.html.erb
<h1>Corresponding Secretary Admin - Manage Candidates</h1>

<%= link_to "Back to Csec Admin", admin_csec_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Classes Signed Up For</th>
  </tr>
  <% @users.each do |person| %>
    <tr>
      <td>
        <%= link_to person.full_name, person %>
      </td>
      <td>
        <% person.course_surveys.includes(course_offering: :course).each do |course_survey| %>
          <%= course_survey.course_offering.course.course_abbr%>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/csec/manage_classes.html.erb
<h1>Corresponding Secretary Admin - Manage Classes</h1>

<p> <%= link_to "Back to Csec Admin", admin_csec_path %> </p>

<script>
  function set_all_max_surveyors() {
    var x = $('#global_max_surveyors').val();
    $('#manage_classes_table input[type="text"]').each( function(index) {
      $(this).attr('value', x);
    });
  }
</script>

<p> <%= link_to 'Set all max surveyors', 'javascript:;', onclick: "set_all_max_surveyors();" %> <%= text_field_tag "global_max_surveyors" %> </p>
<%= form_tag nil do %>
  <table id="manage_classes_table">
    <tr>
      <th>Status</th>
      <th>Course Number</th>
      <th>Section</th>
      <th>Time</th>
      <th>Loc</th>
      <th># Students</th>
      <th>Notes</th>
      <th>Max Surveyors</th>
      <th>Surveyors</th>
      <th></th>
    </tr>
    <% @coursesurveys.each do |coursesurvey| %>
      <tr>
        <td><%= select_tag "survey#{coursesurvey.id}[status]", options_for_select(CourseSurvey.statusmap.invert.to_a.sort{|a,b| a.last <=> b.last }, selected: coursesurvey.status ) %></td>
        <td><%= link_to coursesurvey.course_offering.course.course_abbr, 'admin_courses_show_path(*coursesurvey.klass.course.slug)' %></td>
        <td><%= link_to coursesurvey.course_offering.section.to_s.center(5).gsub(' ','&nbsp').html_safe, 'admin_klasses_edit_path(coursesurvey.klass)' %></td>
        <td><%= coursesurvey.course_offering.time %></td>
        <td><%= coursesurvey.course_offering.location %></td>
        <td><%= coursesurvey.course_offering.num_students %></td>
        <td><%= coursesurvey.course_offering.notes %></td>
        <td><%= text_field_tag "survey#{coursesurvey.id}[max_surveyors]", coursesurvey.max_surveyors %></td>
        <td>
          <% coursesurvey.users.each do |person| %>
            <%# link_to person.full_name, admin_csec_coursesurvey_path(coursesurvey) %>
            <%= link_to person.full_name, person %>
            <%= "," if coursesurvey.users.last != person %>
          <% end %>
        </td>
        <td><%= link_to "Edit", admin_csec_coursesurvey_path(coursesurvey) %></td>
      </tr>
    <% end %>
  </table>

  <%= submit_tag %>
<% end %>

app/views/admin/csec/select_classes.html.erb
<h1>Corresponding Secretary Admin - Select Classes to Survey</h1>

<%= link_to "Back to Csec Admin", admin_csec_path %>
Check Everything
<input type="checkbox" onclick="checkAll(this)">

<%= form_tag nil do %>
  <div class="field">
    <%= label_tag :coursesurveys_active, "Allow Course Survey Signups" %>
    <%= check_box_tag :coursesurveys_active, true, MemberSemester.current.coursesurveys_active %>
  </div>
  <table>
    <tr>
      <th>Needs Survey</th>
      <th>Course Number</th>
      <th>Section</th>
      <th>Notes</th>
    </tr>
    <% for offering in @offerings %>
      <tr>
        <td><%= check_box_tag "offering#{offering.id}", true, !offering.course_survey.nil? %></td>
        <td><%= offering.course.course_abbr %></td>
        <td><%= offering.section %></td>
        <td><%= offering.notes %></td>
      </tr>
    <% end %>
  </table>
  <%= submit_tag %>
<% end %>

<script>
  function checkAll(bx) {
    var cbs = document.getElementsByTagName('input');
    for(var i=0; i < cbs.length; i++) {
      if(cbs[i].type == 'checkbox') {
        cbs[i].checked = bx.checked;
      }
    }
  }
</script>

app/views/admin/csec/upload_surveys.html.erb
<div class="directions">
  <h3>Directions</h3>
  <%= raw [
        "Upload prof data", [
          "Choose file to upload",
          "Click upload and wait a while for processing to finish (dry run)",
          "If errors occurred, fix them or contact compserv.",
          "Else, if no errors occurred, upload data for realsies.", [
            "First verify that the data looks right. Entities that are NEW will have a few nil fields. SurveyAnswers that rely on NEW entities might also have some nil fields, including stats, these will be corrected in the final run.",
            "Choose THE SAME FILE from step 1.1. It won't be verified that you actually uploaded the same file.",
            "Tick the box marked 'Save'. Read and accept the directions there.",
            "Click Upload to reprocess and commit the new data.",
            "Look for \"Save = true\" and no errors, which indicates success. All missing data should now be populated; whatever shows in the Info section is exactly what's in the database. Go verify that things show up in the course surveys section (if not, the server cache may need to be cleared)."
            ]
        ],
        "Upload TA data"
      ].to_ul 'ol'
   %>
  <h3>Fine print</h3>
  <%= raw [
        "For the time being, all sections default to 0. This is because, for historical reasons, one section corresponds to exactly one instructor, and all TAs are registered for all sections. This shall be fixed in the future.",
        "Behavior is undefined when uploading the same data multiple times, or uploading TAs before profs. It should be fine, but have a web-dev handy just in case."
      ].to_ul
   %>
</div>
<div class="upload-form">
  <small>Upload raw survey data as <b>CSV</b> (a.k.a. doublequoted and comma-delimited).</small>
  <%= form_tag nil, :multipart=>true, :method=>:post do %>
    <%= file_field_tag :file, :accept => 'text/csv' %>
    <%= submit_tag 'Upload', :disable_with => "Processing..." %>
    <br/>
    <%= label_tag :save, "Save", :for => :save %>
    <%= check_box_tag :save, "1", false, :disabled => !@allow_save, :onclick => "if(this.checked) this.checked=confirm(\"Are you sure? If so, click OK and re-select the file to be uploaded. Make sure compserv has made a backup recently before you do this.\\n\\nBtw, this could take a while. DO NOT resubmit/refresh until the page comes back to you. If an error occurs, first check to see if the data was imported (it probably wasn't), then go back to the upload form via the url, NOT with back/refresh.\");" %>
    &nbsp;&nbsp;&nbsp;
    <%= label_tag :ta, "TA?", :for => :ta %>
    <%= check_box_tag :ta, "1", @ta, :disabled => @allow_save %>
  <%- end -%>
</div>

<div class="info-box">
  <div class="errors">
    Errors:
    <%= raw @results[:errors].to_ul %>
  </div>
  <div class="info">
    Info:
    <%= raw @results[:info].collect(&:to_ul).join('<br/>') %>
  </div>
</div>