config/routes.rb
HknRails::Application.routes.draw do

  match "courseguides", to: "courseguides#index", via: :get, as: "courseguides"
  match "courseguides/:dept/:name", to: "courseguides#show", via: :get, as: "courseguide_show"
  match "courseguides/edit/:dept/:name", to: "courseguides#edit", via: :get, as: "courseguide_edit"
  match "courseguides/edit/:dept/:name", to: "courseguides#update", via: :post, as: "courseguides_update"

  root to: "pages#home"

  devise_for :users, controllers: { registrations: "registrations" }

  match 'notifications/read', to: 'notifications#index', via: :get, as: "notifications"

  match "dept_tours/success", to: "dept_tours#success", via: :get, as: "dept_tours_success"
  match "dept_tours/:id", to: "dept_tours#respond_to_tour", via: :post
  match "exams/search(/:q)", to: "exams#search", via: :get, :as => :exams_search
  match "exams/course/:dept_abbr/:full_course_number", to: "exams#course", via: :get, :as => :exams_course
  match "users/approve/:id", to: "users#approve", via: :post, as: "users_approve"
  match "users/list(/:category)", to: "users#list", via: :get, as: "users_list"
  match "users/roles/:id", to: "users#roles", via: :get, as: "edit_roles_user"
  match "users/roles/:id", to: "users#alter_roles", via: :post, as: "alter_roles_user"
  match "resumes/upload_for/:user_id" => "resumes#upload_for", via: :get, :as => :resumes_upload_for
  match "resumes/:id/download" => "resumes#download", via: :get, :as => :resume_download
  match "resumes/status_list" => "resumes#status_list", via: :get, :as => :resumes_status_list
  match "resume_books/:id/download_pdf" => "resume_books#download_pdf", via: :get, :as => :resume_book_download_pdf
  match "resume_books/:id/download_iso" => "resume_books#download_iso", via: :get, :as => :resume_book_download_iso
  match "resume_books/missing" => "resume_books#missing", via: :post, :as => :resume_book_missing
  match "resume_books/missing" => "resume_books#missing", via: :get, :as => :resume_book_missing_get
  match 'resumes/include/:id' => "resumes#include", via: :post, :as => :resumes_include
  match 'resumes/exclude/:id' => "resumes#exclude", via: :post, :as => :resumes_exclude
  match 'staff_members_merge' => 'staff_members#merge', via: :get, as: :staff_members_merge
  match 'staff_members_merge' => 'staff_members#merge_post_setup', via: :post, as: :staff_members_merge_post
  match 'staff_members_commit' => 'staff_members#merge_post_commit', via: :post, as: :staff_members_merge_post_commit
  match 'autocomplete_staff_members', to: 'staff_members#autocomplete_staff_members_name', via: :get, as: :autocomplete_staff_members_name

  match 'autocomplete_course_names', to: 'courses#autocomplete_course_names', via: :get, as: :autocomplete_course_name

  match "coursesurveys/course/:dept/:name", to: "coursesurveys#show", via: :get, :as => :coursesurveys_course
  match "coursesurveys/course/:dept", to: "coursesurveys#department", via: :get, :as => :coursesurveys_department
  match "coursesurveys/how-to", to: "pages#coursesurveys_how_to", via: :get, :as => :coursesurveys_how_to
  match "coursesurveys/info-profs", to: "pages#coursesurveys_info_profs", via: :get, :as => :coursesurveys_info_profs
  match "coursesurveys/ferpa", to: "pages#coursesurveys_ferpa", via: :get, :as => :coursesurveys_ferpa

  match 'staff_members/staff/:instructors', to: 'staff_members#instructors', via: :get, as: :staff_member_instructors

  resources :alum
  resources :announcements
  resources :challenges, only: [:create, :update, :index]
  resources :companies
  resources :contacts
  resources :courses
  resources :coursesurveys
  resources :dept_tours
  resources :exams
  resources :indrel_event_types
  resources :indrel_events
  resources :locations
  resources :resumes
  resources :resume_books, except: [:edit, :update]
  resources :resume_book_urls
  resources :staff_members
  resources :users, except: [:new, :create, :index]

  scope "events" do
    match "leaderboard(/:semester)", to: "events#leaderboard", via: :get, as: :event_leaderboard
    match "rsvps", to: "rsvps#my_rsvps", via: :get, as: :my_rsvps
    match "calendar", to: "events#calendar", via: :get, as: "events_calendar"
    match ":category", to: "events#index", via: :get, as: :events_category, constraints: {:category => /(future|past)/}
    # Routes for RSVP confirmation page
    match "confirm_rsvps/:role" => "events#confirm_rsvps_index", via: :get, :as => :confirm_rsvps_index
    match "confirm_rsvps/:role/event/:id" => "events#confirm_rsvps", via: :get, :as => :confirm_rsvps
    match "confirm/:id" => "rsvps#confirm", via: :get, :as => :confirm_rsvp
    match "unconfirm/:id" => "rsvps#unconfirm", via: :get, :as => :unconfirm_rsvp
    match "reject/:id" => "rsvps#reject", via: :get, :as => :reject_rsvp
  end

  resources :events do
    resources :rsvps, shallow: true
  end

  scope "candidate" do
    match "quiz", to: "candidate#quiz", via: :get, as: "candidate_quiz"
    match "submit_quiz", to: "candidate#submit_quiz", via: :post, as: "candidate_submit_quiz"
    match "portal", to: 'candidate#portal', via: :get, as: "candidate_portal"
    match "application", to: 'candidate#application', via: :get, as: "candidate_application"
    match "application", to: 'candidate#submit_app', via: :post, as: "candidate_submit_app"
    match "autocomplete_officer_name", to: "candidate#autocomplete_officer_name", via: :get, as: "autocomplete_officer_name"
  end

  scope "indrel" do
    match "/", to: "indrel#why_hkn", via: :get, as: "indrel"
    match "contact_us", to: "indrel#contact_us", via: :get, as: "indrel_contact_us"
    match "career_fair", to: "indrel#career_fair", via: :get, as: "career_fair"
    match "resume_books", to: "indrel#resume_books", via: :get, as: "resume_books_about"
    match "resume_books/order", to: "indrel#resume_books_order", via: :get, :as => "resume_books_order"
    match "resume_books/order", to: "indrel#resume_books_transaction_id", via: :post, :as => "resume_books_transaction_id"
    match "resume_books/success", to: "indrel#resume_books_order_paypal_success", via: :get, :as => "resume_books_paypal_success"
    match "resume_books/order_email", to: "indrel#resume_books_order_email", via: :get, :as => "resume_books_order_email"
    match "resume_books/order_email", to: "indrel#resume_books_order_email_post", via: :post, :as => "resume_books_order_email_post"
    # post  "resume-books/order_email"        => "indrel#resume_book_order_post",        :as => "resume_book_order_post"
    scope "infosessions" do
      match "/", to: "infosession_requests#about", via: :get, as: "infosessions"
      match "registration", to: "infosession_requests#new", via: :get, as: "new_infosession_request"
      match "registration", to: "infosession_requests#create", via: :post, as: "create_infosession_request"
    end
  end

  #About HKN
  scope 'about' do
    match 'contact', to: "pages#contact", via: :get, as: "about_contact"
    match 'officers(/:semester)', to: "pages#officers", via: :get, as: "about_officers"
    match 'committee_members(/:semester)', to: "pages#committee_members", via: :get, as: "about_committee_members"
  end

  scope 'bridge' do
    resources :slideshows
    resources :yearbooks
  end

  namespace :admin do
    scope "csec" do
      match "/", to: "csec#index", via: :get, as: :csec
      match "select_classes", to: "csec#select_classes", via: :get, as: :csec_select_classes
      match "select_classes", to: "csec#select_classes_post", via: :post, as: :csec_select_classes_post
      match "manage_classes", to: "csec#manage_classes", via: :get, as: :csec_manage_classes
      match "manage_classes", to: "csec#manage_classes_post", via: :post, as: :csec_manage_classes_post
      match "manage_candidates", to: "csec#manage_candidates", via: :get, as: :csec_manage_candidates
      match "upload_surveys", to: "csec#upload_surveys", via: :get, as: :csec_upload_surveys
      match "upload_surveys", to: "csec#upload_surveys_post", via: :post, as: :csec_upload_surveys_post
      match 'coursesurveys/:id', to: 'csec#coursesurvey_show', via: :get, as: :csec_coursesurvey
      match 'coursesurveys/:coursesurvey_id/remove/:user_id', to: 'csec#coursesurvey_remove', via: :delete, as: :csec_coursesurvey_remove
    end
    scope "vp" do
      match "/", to: "vp#index", via: :get, as: :vp
      match "applications", to: "vp#applications", via: :get, as: :cand_applications
      match "applications/byperson", to: "vp#byperson", via: :get, as: :cand_byperson
      match "applications/bycommittee", to: "vp#bycommittee", via: :get, as: :cand_bycommittee
      match "applications/byperson_withoutapp", to: "vp#byperson_without_application", via: :get, as: :cand_byperson_without_application
      match "super_page(/:semester)", to: "vp#super_page", via: :get, as: :vp_super_page
      match "promote_candidate_path", to: "vp#promote_candidate", via: :post, as: :vp_promote_candidate
    end
    match "pres", to: "pres#index", via: :get, as: :pres
    scope "bridge" do
      match "/", to: "bridge#index", via: :get, as: :bridge
      match "officer_photo_upload", to: "bridge#officer_photo_index", via: :get, as: :bridge_officer_index
      match "officer_photo_upload", to: "bridge#officer_photo_upload", via: :post, as: :bridge_officer_upload
    end
    scope "indrel" do
      match "/", to: "indrel#index", via: :get, as: :indrel
    end
    scope "studrel" do
      match "/", to: "studrel#index", via: :get, as: :studrel
    end
  end

end

app/controllers/courseguides_controller.rb
class CourseguidesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update]
  before_filter :authenticate_tutoring!, :only=>[:edit, :update]

  def index
  end

  def show
    redirect_to coursesurveys_search_path("#{params[:dept]} #{params[:course]}") and return unless @course
  end

  def edit
    redirect_to coursesurveys_path, alert: "Error: No such course." and return unless @course
  end

  def update
    redirect_to coursesurveys_path, alert: "Error: That course does not exist." and return unless @course
    if @course.update_attribute(:course_guide, params[:course_guide])
      redirect_to courseguide_show_path, notice: "Successfully updated the course guide for #{@course.course_abbr}."
    else
      redirect_to courseguide_edit_path, alert: "Error updating the entry: #{@course.errors.inspect}"
    end
  end

  def set_course
    @course = Course.find_by_department_and_course_name(params[:dept], params[:name])
  end
end

app/views/courseguides/_csmap.html.erb
	<map id="csmap09" name="csmap09">
    <area coords="301,90,28"  href="<%= courseguide_show_path "CS","61A" %>" shape="circle" alt="CS61A" />
    <area coords="434,290,28" href="<%= courseguide_show_path "CS","61B" %>" shape="circle" alt="CS61B" />
    <area coords="157,290,28" href="<%= courseguide_show_path "CS","61C" %>" shape="circle" alt="CS61C" />
    <area coords="299,280,28" href="<%= courseguide_show_path "CS","70" %>"  shape="circle" alt="CS70"  />
    <area coords="90,145,28"  href="<%= courseguide_show_path "CS","150" %>" shape="circle" alt="CS150" />
    <area coords="179,146,28" href="<%= courseguide_show_path "CS","152" %>" shape="circle" alt="CS152" />
    <area coords="256,601,28" href="<%= courseguide_show_path "CS","160" %>" shape="circle" alt="CS160" />
    <area coords="57,423,28"  href="<%= courseguide_show_path "CS","161" %>" shape="circle" alt="CS161" />
    <area coords="80,501,28"  href="<%= courseguide_show_path "CS","162" %>" shape="circle" alt="CS162" />
    <area coords="123,556,28" href="<%= courseguide_show_path "CS","164" %>" shape="circle" alt="CS164" />
    <area coords="190,590,28" href="<%= courseguide_show_path "CS","169" %>" shape="circle" alt="CS169" />
    <area coords="490,179,28" href="<%= courseguide_show_path "CS","170" %>" shape="circle" alt="CS170" />
    <area coords="434,112,28" href="<%= courseguide_show_path "CS","172" %>" shape="circle" alt="CS172" />
    <area coords="545,112,28" href="<%= courseguide_show_path "CS","174" %>" shape="circle" alt="CS174" />
    <area coords="390,590,28" href="<%= courseguide_show_path "CS","184" %>" shape="circle" alt="CS184" />
    <area coords="479,545,28" href="<%= courseguide_show_path "CS","186" %>" shape="circle" alt="CS186" />
    <area coords="534,445,28" href="<%= courseguide_show_path "CS","188" %>" shape="circle" alt="CS188" />
	</map>
  <%= image_tag "site/cs-prereq-chart.png", :alt => "Computer Science Courses", :usemap => "#csmap09" %>

app/views/courseguides/_eemap.html.erb
	<map id="eemap09" name="eemap09">
    <area coords="428,266,28" href="<%= courseguide_show_path "EE","20N" %>"  shape="circle" alt="EE20N"  />
    <area coords="161,267,28" href="<%= courseguide_show_path "EE","40" %>"   shape="circle" alt="EE40"   />
    <area coords="228,356,28" href="<%= courseguide_show_path "EE","105" %>"  shape="circle" alt="EE105"  />
    <area coords="294,268,28" href="<%= courseguide_show_path "EE","117" %>"  shape="circle" alt="EE117"  />
    <area coords="462,135,28" href="<%= courseguide_show_path "EE","118" %>"  shape="circle" alt="EE118"  />
    <area coords="528,135,28" href="<%= courseguide_show_path "EE","119" %>"  shape="circle" alt="EE119"  />
    <area coords="361,357,28" href="<%= courseguide_show_path "EE","120" %>"  shape="circle" alt="EE120"  />
    <area coords="551,423,28" href="<%= courseguide_show_path "EE","121" %>"  shape="circle" alt="EE121"  />
    <area coords="551,268,28" href="<%= courseguide_show_path "EE","122" %>"  shape="circle" alt="EE122"  />
    <area coords="506,545,28" href="<%= courseguide_show_path "EE","123" %>"  shape="circle" alt="EE123"  />
    <area coords="407,568,28" href="<%= courseguide_show_path "EE","125" %>"  shape="circle" alt="EE125"  />
    <area coords="550,346,28" href="<%= courseguide_show_path "EE","126" %>"  shape="circle" alt="EE126"  />
    <area coords="483,457,28" href="<%= courseguide_show_path "EE","128" %>"  shape="circle" alt="EE128"  />
    <area coords="439,512,28" href="<%= courseguide_show_path "EE","129" %>"  shape="circle" alt="EE129"  />
    <area coords="116,445,28" href="<%= courseguide_show_path "EE","130" %>"  shape="circle" alt="EE130"  />
    <area coords="61,556,28"  href="<%= courseguide_show_path "EE","131" %>"  shape="circle" alt="EE131"  />
    <area coords="50,368,28"  href="<%= courseguide_show_path "EE","133" %>"  shape="circle" alt="EE133"  />
    <area coords="250,479,28" href="<%= courseguide_show_path "EE","140" %>"  shape="circle" alt="EE140"  />
    <area coords="149,546,28" href="<%= courseguide_show_path "EE","141" %>"  shape="circle" alt="EE141"  />
    <area coords="250,568,28" href="<%= courseguide_show_path "EE","142" %>"  shape="circle" alt="EE142"  />
    <area coords="49,267,28"  href="<%= courseguide_show_path "EE","143" %>"  shape="circle" alt="EE143"  />
    <area coords="49,457,28"  href="<%= courseguide_show_path "EE","144" %>"  shape="circle" alt="EE144"  />
    <area coords="261,134,28" href="<%= courseguide_show_path "EE","145M" %>" shape="circle" alt="EE145M" />
    <area coords="194,134,28" href="<%= courseguide_show_path "EE","145L" %>" shape="circle" alt="EE145L" />
    <area coords="328,134,28" href="<%= courseguide_show_path "EE","145B" %>" shape="circle" alt="EE145B" />
    <area coords="295,356,28" href="<%= courseguide_show_path "CS","150" %>"  shape="circle" alt="CS150"  />
    <area coords="351,535,28" href="<%= courseguide_show_path "EE","192" %>"  shape="circle" alt="EE192"  />
	</map>
  <%= image_tag "site/ee-prereq-chart.png", :alt => "Electrical Engineering Courses", :usemap => "#eemap09" %>

app/views/courseguides/edit.html.erb
<h1>
  <%= "Editing Course Guide for #{@course.course_abbr} : #{@course.name}" %>
</h1>
<p>
  <%= link_to "View Course Guide", courseguide_show_path(@course.department, @course.course_name) %>
</p>
<%= form_tag nil do %>
  <div class="field">
    <%= text_area_tag :course_guide, @course.course_guide, style: "width:90%;min-height:500px;" %>
  </div>
  <div class="field-submit">
    <%= submit_tag %>
  </div>
<% end %>

app/views/courseguides/index.html.erb
<div class="trans-bg" id="sidebar">
  <%= render :partial => "coursesurveys/quick_nav" %>
</div>
<div id="main">
  <h1>Course Guides</h1>
  <p>
    We offer a comprehensive course guide for all undergraduate level EECS courses here.
  </p>
  <h2>Prerequisite Charts</h2>
  <p>(Click on a course in the images below to see the relevant course guide)</p>
  <%= render :partial => "eemap" %>
  <br/>
  <%= render :partial => "csmap" %>
</div>

app/views/courseguides/show.html.erb
<div class="trans-bg" id="sidebar">
  <h1>Quicklinks</h1>
  <ul class="plain">
    <li>
      <%= link_to "Course Surveys", coursesurveys_course_path(@course.department, @course.course_name) %>
    </li>
    <li>
      <%= link_to "Exam Archive", exams_course_path(@course.department, @course.course_name) %>
    </li>
    <% if authorize(:tutoring) %>
      <li>
        <%= link_to "Edit this page", courseguide_edit_path(@course.department, @course.course_name) %>
      </li>
    <% end %>
  </ul>
</div>
<div id="main">
  <h1>
    <%= @course.department + @course.course_name %>
    <%= " &mdash; ".html_safe %>
    <%= @course.name %>
    <%= "(#{pluralize(@course.units, "Unit")})" %>
  </h1>
  <% if @course.course_guide.blank? %>
    <p>We're still building the guide for this course, please check back later!</p>
  <% else %>
    <%= Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(@course.course_guide).html_safe %>
  <% end %>
</div>