config/routes.rb
HknRails::Application.routes.draw do

  match "courseguides", to: "courseguides#index", via: :get, as: "courseguides"
  match "courseguides/:dept/:name", to: "courseguides#show", via: :get, as: "courseguide_show"
  match "courseguides/edit/:dept/:name", to: "courseguides#edit", via: :get, as: "courseguide_edit"
  match "courseguides/edit/:dept/:name", to: "courseguides#update", via: :post, as: "courseguides_update"

  root to: "pages#home"

  devise_for :users, controllers: { registrations: "registrations" }

  match 'notifications/read', to: 'notifications#index', via: :get, as: "notifications"

  match "dept_tours/success", to: "dept_tours#success", via: :get, as: "dept_tours_success"
  match "dept_tours/:id", to: "dept_tours#respond_to_tour", via: :post
  match "exams/search(/:q)", to: "exams#search", via: :get, :as => :exams_search
  match "exams/course/:dept_abbr/:full_course_number", to: "exams#course", via: :get, :as => :exams_course
  match "users/approve/:id", to: "users#approve", via: :post, as: "users_approve"
  match "users/list(/:category)", to: "users#list", via: :get, as: "users_list"
  match "users/roles/:id", to: "users#roles", via: :get, as: "edit_roles_user"
  match "users/roles/:id", to: "users#alter_roles", via: :post, as: "alter_roles_user"
  match "resumes/upload_for/:user_id" => "resumes#upload_for", via: :get, :as => :resumes_upload_for
  match "resumes/:id/download" => "resumes#download", via: :get, :as => :resume_download
  match "resumes/status_list" => "resumes#status_list", via: :get, :as => :resumes_status_list
  match "resume_books/:id/download_pdf" => "resume_books#download_pdf", via: :get, :as => :resume_book_download_pdf
  match "resume_books/:id/download_iso" => "resume_books#download_iso", via: :get, :as => :resume_book_download_iso
  match "resume_books/missing" => "resume_books#missing", via: :post, :as => :resume_book_missing
  match "resume_books/missing" => "resume_books#missing", via: :get, :as => :resume_book_missing_get
  match 'resumes/include/:id' => "resumes#include", via: :post, :as => :resumes_include
  match 'resumes/exclude/:id' => "resumes#exclude", via: :post, :as => :resumes_exclude
  match 'staff_members_merge' => 'staff_members#merge', via: :get, as: :staff_members_merge
  match 'staff_members_merge' => 'staff_members#merge_post_setup', via: :post, as: :staff_members_merge_post
  match 'staff_members_commit' => 'staff_members#merge_post_commit', via: :post, as: :staff_members_merge_post_commit
  match 'autocomplete_staff_members', to: 'staff_members#autocomplete_staff_members_name', via: :get, as: :autocomplete_staff_members_name

  match 'autocomplete_course_names', to: 'courses#autocomplete_course_names', via: :get, as: :autocomplete_course_name

  match "coursesurveys/course/:dept/:name", to: "coursesurveys#show", via: :get, :as => :coursesurveys_course
  match "coursesurveys/course/:dept", to: "coursesurveys#department", via: :get, :as => :coursesurveys_department
  match "coursesurveys/how-to", to: "pages#coursesurveys_how_to", via: :get, :as => :coursesurveys_how_to
  match "coursesurveys/info-profs", to: "pages#coursesurveys_info_profs", via: :get, :as => :coursesurveys_info_profs
  match "coursesurveys/ferpa", to: "pages#coursesurveys_ferpa", via: :get, :as => :coursesurveys_ferpa

  match 'staff_members/staff/:instructors', to: 'staff_members#instructors', via: :get, as: :staff_member_instructors

  resources :alum
  resources :announcements
  resources :challenges, only: [:create, :update, :index]
  resources :companies
  resources :contacts
  resources :courses
  resources :coursesurveys
  resources :dept_tours
  resources :exams
  resources :indrel_event_types
  resources :indrel_events
  resources :locations
  resources :resumes
  resources :resume_books, except: [:edit, :update]
  resources :resume_book_urls
  resources :staff_members
  resources :users, except: [:new, :create, :index]

  scope "events" do
    match "leaderboard(/:semester)", to: "events#leaderboard", via: :get, as: :event_leaderboard
    match "rsvps", to: "rsvps#my_rsvps", via: :get, as: :my_rsvps
    match "calendar", to: "events#calendar", via: :get, as: "events_calendar"
    match ":category", to: "events#index", via: :get, as: :events_category, constraints: {:category => /(future|past)/}
    # Routes for RSVP confirmation page
    match "confirm_rsvps/:role" => "events#confirm_rsvps_index", via: :get, :as => :confirm_rsvps_index
    match "confirm_rsvps/:role/event/:id" => "events#confirm_rsvps", via: :get, :as => :confirm_rsvps
    match "confirm/:id" => "rsvps#confirm", via: :get, :as => :confirm_rsvp
    match "unconfirm/:id" => "rsvps#unconfirm", via: :get, :as => :unconfirm_rsvp
    match "reject/:id" => "rsvps#reject", via: :get, :as => :reject_rsvp
  end

  resources :events do
    resources :rsvps, shallow: true
  end

  scope "candidate" do
    match "quiz", to: "candidate#quiz", via: :get, as: "candidate_quiz"
    match "submit_quiz", to: "candidate#submit_quiz", via: :post, as: "candidate_submit_quiz"
    match "portal", to: 'candidate#portal', via: :get, as: "candidate_portal"
    match "application", to: 'candidate#application', via: :get, as: "candidate_application"
    match "application", to: 'candidate#submit_app', via: :post, as: "candidate_submit_app"
    match "autocomplete_officer_name", to: "candidate#autocomplete_officer_name", via: :get, as: "autocomplete_officer_name"
  end

  scope "indrel" do
    match "/", to: "indrel#why_hkn", via: :get, as: "indrel"
    match "contact_us", to: "indrel#contact_us", via: :get, as: "indrel_contact_us"
    match "career_fair", to: "indrel#career_fair", via: :get, as: "career_fair"
    match "resume_books", to: "indrel#resume_books", via: :get, as: "resume_books_about"
    match "resume_books/order", to: "indrel#resume_books_order", via: :get, :as => "resume_books_order"
    match "resume_books/order", to: "indrel#resume_books_transaction_id", via: :post, :as => "resume_books_transaction_id"
    match "resume_books/success", to: "indrel#resume_books_order_paypal_success", via: :get, :as => "resume_books_paypal_success"
    match "resume_books/order_email", to: "indrel#resume_books_order_email", via: :get, :as => "resume_books_order_email"
    match "resume_books/order_email", to: "indrel#resume_books_order_email_post", via: :post, :as => "resume_books_order_email_post"
    # post  "resume-books/order_email"        => "indrel#resume_book_order_post",        :as => "resume_book_order_post"
    scope "infosessions" do
      match "/", to: "infosession_requests#about", via: :get, as: "infosessions"
      match "registration", to: "infosession_requests#new", via: :get, as: "new_infosession_request"
      match "registration", to: "infosession_requests#create", via: :post, as: "create_infosession_request"
    end
  end

  #About HKN
  scope 'about' do
    match 'contact', to: "pages#contact", via: :get, as: "about_contact"
    match 'officers(/:semester)', to: "pages#officers", via: :get, as: "about_officers"
    match 'committee_members(/:semester)', to: "pages#committee_members", via: :get, as: "about_committee_members"
  end

  scope 'bridge' do
    resources :slideshows
    resources :yearbooks
  end

  namespace :admin do
    scope "csec" do
      match "/", to: "csec#index", via: :get, as: :csec
      match "select_classes", to: "csec#select_classes", via: :get, as: :csec_select_classes
      match "select_classes", to: "csec#select_classes_post", via: :post, as: :csec_select_classes_post
      match "manage_classes", to: "csec#manage_classes", via: :get, as: :csec_manage_classes
      match "manage_classes", to: "csec#manage_classes_post", via: :post, as: :csec_manage_classes_post
      match "manage_candidates", to: "csec#manage_candidates", via: :get, as: :csec_manage_candidates
      match "upload_surveys", to: "csec#upload_surveys", via: :get, as: :csec_upload_surveys
      match "upload_surveys", to: "csec#upload_surveys_post", via: :post, as: :csec_upload_surveys_post
      match 'coursesurveys/:id', to: 'csec#coursesurvey_show', via: :get, as: :csec_coursesurvey
      match 'coursesurveys/:coursesurvey_id/remove/:user_id', to: 'csec#coursesurvey_remove', via: :delete, as: :csec_coursesurvey_remove
    end
    scope "vp" do
      match "/", to: "vp#index", via: :get, as: :vp
      match "applications", to: "vp#applications", via: :get, as: :cand_applications
      match "applications/byperson", to: "vp#byperson", via: :get, as: :cand_byperson
      match "applications/bycommittee", to: "vp#bycommittee", via: :get, as: :cand_bycommittee
      match "applications/byperson_withoutapp", to: "vp#byperson_without_application", via: :get, as: :cand_byperson_without_application
      match "super_page(/:semester)", to: "vp#super_page", via: :get, as: :vp_super_page
      match "promote_candidate_path", to: "vp#promote_candidate", via: :post, as: :vp_promote_candidate
    end
    match "pres", to: "pres#index", via: :get, as: :pres
    scope "bridge" do
      match "/", to: "bridge#index", via: :get, as: :bridge
      match "officer_photo_upload", to: "bridge#officer_photo_index", via: :get, as: :bridge_officer_index
      match "officer_photo_upload", to: "bridge#officer_photo_upload", via: :post, as: :bridge_officer_upload
    end
    scope "indrel" do
      match "/", to: "indrel#index", via: :get, as: :indrel
    end
    scope "studrel" do
      match "/", to: "studrel#index", via: :get, as: :studrel
    end
  end

end

app/models/rsvp.rb
# == Schema Information
#
# Table name: rsvps
#
#  id                     :integer          not null, primary key
#  user_id                :integer
#  event_id               :integer
#  confirmed              :string(255)
#  confirmed_by           :integer
#  confirmed_at           :datetime
#  created_at             :datetime
#  updated_at             :datetime
#  comment                :string(255)
#  transportation_ability :integer
#

class Rsvp < ActiveRecord::Base
  before_validation :set_default_transportation

  TRANSPORT_ENUM = [
    [ 'I need a ride', -1 ],
    [ "Don't worry about me", 0 ],
    [ 'I have a small sedan (4 seats)', 3 ],
    [ 'I have a sedan (5 seats)', 4 ],
    [ 'I have a minivan (7 seats)', 6 ],
  ]

  Confirmed   = 't'
  Unconfirmed = 'f'
  Rejected    = 'r'

  belongs_to :user
  belongs_to :event

  validates :user_id, presence: true
  validates :event_id, presence: true
  validates :comment, length: { maximum: 300 }
  validates_inclusion_of :confirmed, :in => [Confirmed, Unconfirmed, Rejected, nil]

  def need_transportation
    event and event.need_transportation?
  end

  private
    def set_default_transportation
      if self.need_transportation
        self.transportation_ability ||= TRANSPORT_ENUM.first.last
      end
    end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy, :confirm, :unconfirm, :reject]
  before_filter :validate_owner!, only: [:edit, :update, :destroy]
  before_filter :vp_or_pres!, only: [:confirm, :unconfirm, :reject]
  before_filter :authenticate_user!
  before_filter :get_event, except: :my_rsvps
  before_filter :rsvp_permission!, only: [:new, :create]

  # GET /rsvps
  # GET /rsvps.xml
  def index
    # Most recently created RSVPs will show on top of the list
    @rsvps = @event.rsvps.order("created_at DESC").includes(:user)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rsvps }
    end
  end

  # GET /rsvps/1
  # GET /rsvps/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rsvp }
    end
  end

  # GET /rsvps/new
  # GET /rsvps/new.xml
  def new
    redirect_to event_rsvps_path(params[:event_id].to_i), notice: "you've already rsvp'd" and return if current_user.events.pluck(:id).include?(params[:event_id].to_i)
    @rsvp = Rsvp.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rsvp }
    end
  end

  # GET /rsvps/1/edit
  def edit
  end

  # POST /rsvps
  # POST /rsvps.xml
  def create
    redirect_to event_rsvps_path(params[:event_id].to_i), notice: "you've already rsvp'd" and return if current_user.events.pluck(:id).include?(params[:event_id].to_i)
    @rsvp = Rsvp.new(rsvp_params)
    @rsvp.event = @event
    @rsvp.user = current_user
    @rsvp.confirmed = Rsvp::Unconfirmed

    respond_to do |format|
      if @rsvp.save
        RSVPMailer.rsvp_email(current_user, @rsvp.event).deliver
        format.html { redirect_to(@event, :notice => 'Thanks for RSVPing! See you there!') }
        format.xml  { render :xml => @rsvp, :status => :created, :location => @rsvp }
      else
        format.html { render :new }
        format.xml  { render :xml => @rsvp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rsvps/1
  # PUT /rsvps/1.xml
  def update

    respond_to do |format|
      if @rsvp.update_attributes(rsvp_params)
        format.html { redirect_to(@event, :notice => 'Rsvp was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :edit }
        format.xml  { render :xml => @rsvp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.xml
  def destroy
    @event = @rsvp.event
    @rsvp.destroy

    respond_to do |format|
      format.html { redirect_to(@event) }
      format.xml  { head :ok }
    end
  end

  def confirm

    role = params[:role] || :candidates

    respond_to do |format|
      if @rsvp.update_attributes(confirmed: Rsvp::Confirmed, confirmed_by: current_user.id, confirmed_at: Time.now)
        format.html { redirect_to(confirm_rsvps_path(@rsvp.event_id, :role => role), :notice => 'Rsvp was confirmed.') }
        format.xml  { render :xml => @rsvp }
      else
        format.html { redirect_to confirm_rsvps_path(@rsvp.event_id, :role => role), :notice => 'Something went wrong.' }
        format.xml  { render :xml => @rsvp.errors, :status => :unprocessable_entity }
      end
    end
  end

  def unconfirm
    @rsvp.update_attributes(confirmed: Rsvp::Unconfirmed, confirmed_by: current_user.id, confirmed_at: Time.now)
    role = params[:role] || "candidates"

    respond_to do |format|
      format.html { redirect_to(confirm_rsvps_path(@rsvp.event_id, :role => role), :notice => 'Confirmation was removed.') }
      format.xml { render :xml => @rsvp }
    end
  end

  def reject
    @rsvp.update_attributes(confirmed: Rsvp::Rejected, confirmed_by: current_user.id, confirmed_at: Time.now)
    role = params[:role] || "candidates"

    respond_to do |format|
      format.html { redirect_to(confirm_rsvps_path(@rsvp.event_id, :role => role), :notice => 'Confirmation was rejected.') }
      format.xml { render :xml => @rsvp }
    end
  end

  def my_rsvps
    @rsvps = current_user.rsvps.includes :event
  end

private

  def set_rsvp
    @rsvp = Rsvp.find(params[:id])
  end

  def vp_or_pres!
    authorize(:vp) || authenticate_pres!
  end

  def validate_owner!
    current_user == @rsvp.user || authenticate_superuser!
  end

  def get_event
    @event = Event.find params[:event_id] unless params[:event_id].blank?
    if !@event
      @event = Rsvp.find(params[:id]).event
    end
  end

  def rsvp_permission!
    if !@event.allows_rsvps? or !@event.can_rsvp? current_user
      redirect_to :root, :notice => "You do not have permission to RSVP for this event"
    end
  end

  def rsvp_params
    params.require(:rsvp).permit(:comment, :transportation_ability)
  end
end

app/views/rsvps/_form.html.erb
<%= form_for([@event, @rsvp]) do |f| %>
  <% if @rsvp.errors.any? %>
    <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>
    <div class="alert alert-danger">
      <% @rsvp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <label>Event</label>
    <div><%= link_to @event.title, @event %></div>
  </div>

  <div class="field">
    <label>User</label>
    <div><%= link_to current_user.full_name, current_user %></div>
  </div>

  <% if @event.need_transportation? %>
  <div class="field">
    <%= f.label :transportation_ability %>
    <%= f.select :transportation_ability, Rsvp::TRANSPORT_ENUM %>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :comment, 'Anything we should know?' %>
    <%= f.text_area :comment %>
  </div>

  <div class="field-submit">
    <%= f.submit 'RSVP!' %>
  </div>
<% end %>

app/views/rsvps/edit.html.erb
<h1>Changing RSVP</h1>

<%= form_for @rsvp do |f| %>
  <% if @rsvp.errors.any? %>
    <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>
    <div class="alert alert-danger">
      <% @rsvp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <label>Event</label>
    <div><%= link_to @event.title, @event %></div>
  </div>

  <div class="field">
    <label>User</label>
    <div><%= link_to current_user.full_name, current_user %></div>
  </div>

  <% if @event.need_transportation? %>
  <div class="field">
    <%= f.label :transportation_ability %>
    <%= f.select :transportation_ability, Rsvp::TRANSPORT_ENUM %>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :comment, 'Anything we should know?' %>
    <%= f.text_area :comment %>
  </div>

  <div class="field-submit">
    <%= f.submit 'RSVP!' %>
  </div>
<% end %>

app/views/rsvps/index.html.erb
<h1>Listing RSVPs for <%= @event.title %></h1>

<table>
  <tr>
    <th>Person</th>
    <th>Comment</th>
    <th>RSVP Date</th>
    <% if @event.need_transportation? %>
      <th>Transportation</th>
    <% end %>
    <th colspan="3">Actions</th>
  </tr>

<% @rsvps.each do |rsvp| %>
  <tr>
    <td><%= rsvp.user.full_name %></td>
    <td><%= rsvp.comment %></td>
    <td><%= rsvp.created_at.strftime('%a %m/%d/%y %I:%M%p') %></td>
    <% if @event.need_transportation? %>
      <td><%= rsvp.transportation_ability %></td>
    <% end %>
    <td><%= link_to 'Show', rsvp_path(rsvp) %></td>
    <% if authorize(:compserv) %>
      <td class='admin'><%= link_to 'Edit', edit_rsvp_path(rsvp) %></td>
      <td class='admin'><%= link_to 'Destroy', rsvp_path(rsvp), data: { confirm: 'Are you sure?' }, method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rsvp', new_event_rsvp_path(@event) %>

app/views/rsvps/my_rsvps.html.erb
<h1>My RSVPs</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Confirmed?</th>
    <th colspan="3">Actions</th>
  </tr>

<% @rsvps.each do |rsvp| %>
  <tr>
    <td><%= rsvp.event.title %></td>
    <td><%= rsvp.confirmed == 't' ? "Yes" : "No" %></td>
    <td><%= link_to 'Show', rsvp_path(rsvp) %></td>
    <% if comm_authorize %>
      <td class='admin'><%= link_to 'Edit', edit_rsvp_path(rsvp) %></td>
      <td class='admin'><%= link_to 'Destroy', rsvp_path(rsvp), data: { confirm: 'Are you sure?' }, :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/rsvps/new.html.erb
<h1>RSVP</h1>

<%= render 'form' %>

app/views/rsvps/show.html.erb
<p>
  <b>Person:</b>
  <%= link_to @rsvp.user.full_name, @rsvp.user %>
</p>

<p>
  <b>Event:</b>
  <%= link_to @rsvp.event.title , @rsvp.event %>
</p>

<p>
  <b>Comment:</b>
  <%= @rsvp.comment %>
</p>

<% if @event.need_transportation? %>
<p>
  <b>Transportation:</b>
  <%= @rsvp.transportation_ability %>
</p>
<% end %>

<% if @rsvp.user == current_user || authorize(:compserv) %>
	<%= link_to 'Edit', edit_rsvp_path(@rsvp) %> |
<% end %>
<%= link_to 'RSVPs Index', event_rsvps_path(@event) %> |
<%= link_to 'Event Details', event_path(@event) %>